# project/mmm-search/.gitlab-ci.yml
include:
  - local: '.gitlab-ci-base.yml'

variables:
  MODULE_PATH: "project/mmm-search"

build-search:
  extends: .application-template

sonar-search:
  extends: .sonar-template
  needs: ["build-search"]

deploy-search-snapshot:
  extends: .deploy-snapshot-template
  needs: ["build-search"]

deploy-search-image:
  extends: .deploy-image-template
  needs: ["build-search"]

deploy-manifests-prod:
  extends: .deploy-cluster-template
  needs: ["deploy-search-image"]
  resource_group: search-deploy-prod
  environment:
    name: production
  variables:
    OVERLAY_PATH: "project/mmm-search/k8s/overlays/prod"
    DEPLOYMENT_NAME: "mmm-search"

rollback-prod:
  extends: .rollback-template
  needs: ["deploy-manifests-prod"]
  resource_group: search-deploy-prod
  variables:
    DEPLOYMENT_NAME: "mmm-search"
    K8S_NAMESPACE: "production"

liquibase-validate:
  extends: .liquibase-validate
  needs: ["build-search"]

liquibase-update:
  extends: .liquibase-update
  needs: ["liquibase-validate"]
