spring:
  application:
    name: spring-security-securitycontext-mockmvc
  datasource:
    driverClassName: org.h2.Driver
    url: "jdbc:h2:mem:testdb"
    username: sa
    password: password
  h2:
    console:
      enabled: true
  security:
    user:
      name: bwgjoseph
      password: password
