# project/mmm-core/.gitlab-ci.yml
include:
  - local: '.gitlab-ci-base.yml'

variables:
  MODULE_PATH: "project/mmm-core"

build-core:
  extends: .application-template

sonar-core:
  extends: .sonar-template
  needs: ["build-core"]

deploy-core-snapshot:
  extends: .deploy-snapshot-template
  needs: ["build-core"]

deploy-core-image:
  extends: .deploy-image-template
  needs: ["build-core"]

deploy-manifests-prod:
  extends: .deploy-cluster-template
  needs: ["deploy-core-image"]
  resource_group: core-deploy-prod
  environment:
    name: production
  variables:
    OVERLAY_PATH: "project/mmm-core/k8s/overlays/prod"
    DEPLOYMENT_NAME: "mmm-core"

rollback-prod:
  extends: .rollback-template
  needs: ["deploy-manifests-prod"]
  resource_group: core-deploy-prod
  variables:
    DEPLOYMENT_NAME: "mmm-core"
    K8S_NAMESPACE: "production"