logging:
  level:
    org:
      springframework:
        security: TRACE
        # this will display Mapping filters logs
        boot:
          web:
            servlet:
              ServletContextInitializerBeans: DEBUG